name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/bb-component-SuperCard
      - uses: actions/checkout@v4
        name: Checkout Super Components Shared code repository
        with:
          repository: poirazis/bb_super_components_shared
          path: ${{ github.workspace }}/bb_super_components_shared
          ref: develop
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Create production plugin bundle
        run: |
          cd ${{ github.workspace }}/bb_super_components_shared
          yarn install
          cd ${{ github.workspace }}/bb-component-SuperCard
          release_version=$(jq -r '.version' package.json)
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
          yarn install
          yarn build
      - name: Perform GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ env.RELEASE_VERSION }}
          tag_name: v${{ env.RELEASE_VERSION }}
          generate_release_notes: true
          files: ${{ github.workspace }}/bb-component-SuperCard/dist/*.tar.gz
